// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchVendor(arg1) {
  return window['go']['main']['App']['FetchVendor'](arg1);
}

export function GetVendor(arg1) {
  return window['go']['main']['App']['GetVendor'](arg1);
}

export function GetVendorNames() {
  return window['go']['main']['App']['GetVendorNames']();
}
