// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wfmplatefficiency} from '../models';

export function FetchVendor(arg1:string):Promise<string>;

export function GetVendor(arg1:string):Promise<wfmplatefficiency.Vendor>;

export function GetVendorNames():Promise<Array<string>>;
